services:
  app:
    container_name: ixy
    build:
      context: backend
      target: ${TARGET_STAGE}
    environment:
      - FORCE_COLOR=1
      - BASE_URL=https://placekitten.com
      - REVALIDATE_AFTER=1
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./backend/src:/home/node/app/src:ro
      - cache:/home/node/cache
  ui:
    container_name: ixy-ui
    build:
      context: frontend
      target: ${TARGET_STAGE}
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./frontend/src:/home/node/app/src:ro
volumes:
  cache:
