kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ixy.serviceAccountName" . }}-{{ .Values.role.name }}
  labels:
    {{- include "ixy.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ixy.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.role.name }}