kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.role.name }}
  labels:
    {{- include "ixy.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]