apiVersion: v1
kind: Service
metadata:
  name: {{ include "ixy.fullname" . }}
  labels:
    {{- include "ixy.labels" . | nindent 4 }}
spec:
  {{- if .Values.develop }}
  type: NodePort
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.develop }}
      nodePort: 30001
      {{- end }}
  selector:
    {{- include "ixy.selectorLabels" . | nindent 4 }}

