{{- if and .Values.ui.enabled .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ixy.fullname.ui" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- with .Values.ui.ingress.annotations }}
    {{ . | toYaml | nindent 4 }}
      {{- end }}
  {{- with .Values.ui.ingress.labels }}
  labels:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ui.ingress.hostname }}
      http:
        paths:
          - path: /api/(.+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "ixy.fullname" . }}
                port:
                    number: {{ .Values.service.port }}
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "ixy.fullname.ui" . }}
                port:
                  number: {{ .Values.ui.service.port }}
{{- end }}