{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ixy.fullname.ui" . }}
  labels:
    {{- include "ixy.labels" . | nindent 4 }}
spec:
  {{- if .Values.develop }}
  type: NodePort
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.develop }}
      nodePort: 30002
      {{- end }}
  selector:
      {{- include "ixy.selectorLabels.ui" . | nindent 4 }}
{{- end }}