name: Build new version

on:
  push:
    tags:
      - "*"

jobs:
  build-backend:
    runs-on: ubuntu-latest
    if: "!contains(github.ref_name, 'ixy-')"   # skip builds if tag contains 'ixy-'
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            neoskop/ixy:${{ github.ref_name }}
            neoskop/ixy:latest

  build-frontend:
    runs-on: ubuntu-latest
    if: "!contains(github.ref_name, 'ixy-')"   # skip builds if tag contains 'ixy-'
    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend image (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            neoskop/ixy-ui:${{ github.ref_name }}
            neoskop/ixy-ui:latest
